### ISSUE TITLE
ToDo

### ISSUE THREAD

**Issue by bmuenzenmeyer** [pattern-lab/starterkit-mustache-webdesignday-complete#1]
- [ ] Slice into smaller starterkits to match the exercise start / ends
  - [ ] Each with their own repository
  - [ ] Add each to https://github.com/pattern-lab/webdesignday-2016
- [ ] Clean up any CSS
- [ ] Run CSS through a prefixer of some sort
- [ ] Add a couple more `.md` files as examples
- [ ] Add link variables to the listitems
- [ ] Improve the footer, it feels bare
- [ ] Add more content to home page
- [ ] Reconsider manuscript styling
- [ ] More browser testing (Chrome, FF, Edge looked good)

**Comment by bmuenzenmeyer** [comment]
Only work remaining is slicing into bits and pushing to the proper branches, testing, and some rejiggered design if time allows.
